name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cloud189-liaoning-person.oos-

lnsy.ctyunapi.cn/e32b2548-c80c-4297-acf3-f3309b272519?x-amz-

UFID=11541210602329155&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-

SHID=169344678&x-amz-FSIZE=2051256752&Expires=1592301074&x-amz-

UID=741439743&response-content-disposition=attachment

%3Bfilename%3D%22MIUI12mi6_06_16.zip

%22&AWSAccessKeyId=532482dfdc85e5d60592&x-amz-

limitrate=10240&x-amz-CLOUDTYPEIN=PERSON&x-amz-

CLIENTTYPEIN=WEB&Signature=c9Na8LXxqR9gqoJsXNAnp75xoAs%3D
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == 

github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php 

/etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm 

llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules 

https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         run: |
           7za a -t7z -r MI6_Aonly.7z ErfanGSIs/output/*
       
       - name: Upload Aonly GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet MI6_Aonly.7z
           
#       - name: Make clean
#         run: sudo rm -rf ErfanGSIs/output/*
         
#       - name: Download Stock Rom & Generate AB GSI
#         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

#       - name: 7z AB GSI
#         run: |
#           7za a -t7z -r AB_GSI.7z ErfanGSIs/output/*

#       - name: Upload AB GSI to WeTransfer
#         run: |
#              curl -sL https://git.io/file-transfer | sh
#              ./transfer wet AB_GSI.7z
         
            
