name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://cloud189-xizang-person.oos-xzls.ctyunapi.cn/f71d34cc-98f8-4e3f-80de-63f052c1e3dc?x-amz-UFID=81547210159238555&x-amz-CLIENTNETWORK=UNKNOWN&x-amz-SHID=169358309&x-amz-FSIZE=2165191881&Expires=1592481241&x-amz-UID=741439743&response-content-disposition=attachment%3Bfilename%3D%22miui_MI6%C3%A6%C2%B5%C2%8B%C3%A8%C2%AF%C2%95_9.0.zip%22&AWSAccessKeyId=532482dfdc85e5d60592&x-amz-limitrate=10240&x-amz-CLOUDTYPEIN=PERSON&x-amz-CLIENTTYPEIN=WEB&Signature=6xr6TXhvNOOR1MIFG/hNHclnyFc%3D
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo apt update
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         run: |
           7za a -t7z -r 06181.7z ErfanGSIs/output/*
       
       - name: Upload Aonly GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet 06181.7z
           
#       - name: Make clean
#         run: sudo rm -rf ErfanGSIs/output/*
         
#       - name: Download Stock Rom & Generate AB GSI
#         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

#       - name: 7z AB GSI
#         run: |
#           7za a -t7z -r AB_GSI.7z ErfanGSIs/output/*

#       - name: Upload AB GSI to WeTransfer
#         run: |
#              curl -sL https://git.io/file-transfer | sh
#              ./transfer wet AB_GSI.7z
         
            
