name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://58-49-136-7.ksyungslb.com/bigota.d.miui.com/20.6.23/miui_MI8Lite_20.6.23_89751d475b_10.0.zip?ksy_gslb_referer=https%3A%2F%2Fgithub.com%2FmooseIre%2Fupdate_miui_ota%2Fblob%2Fmaster%2FDevelop%2F%25E5%25B0%258F%25E7%25B1%25B38%25E9%259D%2592%25E6%2598%25A5%25E7%2589%2588.md
  ROM_NAME: MIUI
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo apt update
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         run: |
           7za a -t7z -r 0625_10.7z ErfanGSIs/output/*
       
       - name: Upload Aonly GSI to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet 0625_10.7z
           
#       - name: Make clean
#         run: sudo rm -rf ErfanGSIs/output/*
         
#       - name: Download Stock Rom & Generate AB GSI
#         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

#       - name: 7z AB GSI
#         run: |
#           7za a -t7z -r AB_GSI.7z ErfanGSIs/output/*

#       - name: Upload AB GSI to WeTransfer
#         run: |
#              curl -sL https://git.io/file-transfer | sh
#              ./transfer wet AB_GSI.7z
         
            
